name: flutter_near
description: "A flutter version of Near"
publish_to: 'none'
version: 1.0.7+8

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dart_jts: ^0.2.6
  dart_hydrologis_db: ^1.1.1
  dart_hydrologis_utils: ^0.8.1+2
  sqlite3_flutter_libs: ^0.5.30
  flutter_geopackage: ^0.6.4+2
  # sqlite3: ^2.4.4
  # sqflite: ^2.3.3+1
  # proj4dart: ^2.1.0
  # geoflutterfire2: ^2.3.15
  http: ^1.3.0
  path_provider: ^2.1.5
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  flutter_animate: ^4.5.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.3
  google_maps_flutter: ^2.10.0
  provider: ^6.1.2
  action_slider: ^0.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: assets/logos/logo_1152px.png
  adaptive_icon_background: assets/logos/logo_1152px_adaptive.png
  adaptive_icon_foreground: assets/logos/logo_1152px_adaptive.png
  min_sdk_android: 28