name: flutter_near
description: "A flutter version of Near"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dart_jts: ^0.2.6
  dart_hydrologis_db: ^1.1.1
  dart_hydrologis_utils: ^0.8.1+2
  sqlite3_flutter_libs: ^0.5.24
  flutter_geopackage: ^0.6.4+2
  # sqlite3: ^2.4.4
  # sqflite: ^2.3.3+1
  # proj4dart: ^2.1.0
  xml: ^6.5.0
  http: ^1.2.1
  path_provider: ^2.1.3
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  flutter_animate: ^4.5.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  # geoflutterfire2: ^2.3.15
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
